# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03bca383c5599ad9f85dd54f0edcd31efec5daaa26b848e72c4ce7a11de13db44d499594b2a60fb5670337c570c90909157ce71b6a424e8bf88df92db4d0d980

test:
  secret_key_base: f92884f35ac37a8f2a532c0c7ce639711352c81b09780e899d917be85f428d868150e689bc981cbdc5f9af26055aa7d9f5f223176e69656c1c44bbd0a9bf79cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
